### ISSUE TITLE
Cannot find module 'turf'

### ISSUE THREAD

**Issue by PriyansMurarka** [Veditum/riverbanks#1]
Cloned, ran the command
`node river-buffer.js`

Threw up this error : 
$ node river-buffer.js 
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'turf'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/path/to/code/riverbanks-master/river-buffer.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

$ node -v
v10.1.0

**Comment by PriyansMurarka** [comment]
Did `npm install` and `npm install @turf/line-chuck`

Issue was resolved.
